# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('paid', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'billing',
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
        migrations.CreateModel(
            name='Bookedrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
                ('departure_time', models.DateTimeField(default=datetime.datetime.now)),
                ('relationship', models.CharField(max_length=20)),
                ('advance_receipt_no', models.IntegerField(verbose_name='Advance Reciept')),
            ],
            options={
                'db_table': 'booked_rooms',
                'verbose_name': 'Booked Room',
                'verbose_name_plural': 'Booked Rooms',
            },
        ),
        migrations.CreateModel(
            name='Customerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('no_of_adults', models.IntegerField(verbose_name='No of Adults')),
                ('no_of_children', models.IntegerField(verbose_name='Children')),
                ('purpose', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('aadhar_ID', models.IntegerField(verbose_name='Adhaar')),
                ('phone_no', models.IntegerField(verbose_name='Phone')),
                ('occupation', models.CharField(max_length=20)),
                ('email_ID', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer_details',
                'verbose_name': 'Customer Detail',
                'verbose_name_plural': 'Customer Details',
            },
        ),
        migrations.CreateModel(
            name='Eattendance_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'eattendance_details',
                'verbose_name': 'Eattendance Detail',
                'verbose_name_plural': 'Eattendance Details',
            },
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
                ('DOB', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(verbose_name='Contact')),
                ('email_ID', models.IntegerField(verbose_name='Email')),
                ('aadhar_ID', models.IntegerField(verbose_name='Aadhaar')),
                ('leaves_allowed', models.IntegerField(verbose_name='Leaves Allowed')),
                ('leaves_taken', models.IntegerField(verbose_name='Leaves Taken')),
            ],
            options={
                'db_table': 'employee_details',
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Esalary_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Eattendance_details')),
                ('emp_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Employee_details')),
            ],
            options={
                'db_table': 'esalary_details',
                'verbose_name': 'Esalary Detail',
                'verbose_name_plural': 'Esalary Details',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('reservation_created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('reserved_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'reservation',
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=30)),
                ('resource_availability', models.IntegerField(verbose_name='Resource')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'db_table': 'resources',
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='Roomdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('no_of_adults', models.IntegerField(verbose_name='No of Adults')),
                ('no_of_children', models.IntegerField(verbose_name='Children')),
                ('room_number', models.IntegerField(verbose_name='Room No.')),
                ('rent', models.IntegerField(verbose_name='Rent')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room_details',
                'verbose_name': 'Room Detail',
                'verbose_name_plural': 'Room Details',
            },
        ),
        migrations.CreateModel(
            name='Servicedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'service_details',
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Details',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Roomdetails'),
        ),
        migrations.AddField(
            model_name='eattendance_details',
            name='emp_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Employee_details'),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Customerdetails'),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='resource_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Resources'),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Roomdetails'),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='service_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Servicedetails'),
        ),
        migrations.AddField(
            model_name='billing',
            name='booked_room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Bookedrooms'),
        ),
    ]
