# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0003_bookedrooms_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='email_ID',
            field=models.CharField(max_length=30, verbose_name='Email'),
        ),
    ]
