# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0004_auto_20180217_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='service_price',
            field=models.IntegerField(null=True, verbose_name='Service Price'),
        ),
    ]
