# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0005_servicedetails_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='service_type',
            field=models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('LAUNDRY', 'LAUNDRY'), ('TRANSPORT', 'TRANSPORT')], max_length=10),
        ),
    ]
