# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0007_auto_20180217_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_availability',
            field=models.IntegerField(verbose_name='Resource Availability'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.CharField(choices=[('EXTRA BED', 'EXTRA BED'), ('EXTRA PILLOW', 'EXTRA PILLOW'), ('EXTRA BLANKET', 'EXTRA BLANKET'), ('EXTRA BATH TOWEL', 'EXTRA BATH TOWEL')], max_length=30),
        ),
    ]
