# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0008_auto_20180217_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource_qty',
            field=models.IntegerField(null=True, verbose_name='Resource Qty'),
        ),
    ]
