# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0010_auto_20180217_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_availability',
            field=models.IntegerField(null=True, verbose_name='Resource Availability'),
        ),
    ]
