# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0011_auto_20180217_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='resource_qty',
        ),
        migrations.AlterField(
            model_name='resources',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_name',
            field=models.CharField(max_length=30),
        ),
    ]
