# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0013_auto_20180217_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('NOT AVAILABLE', 'NOT AVAILABLE'), ('CLEANING', 'CLEANING'), ('UNDER REPAIR', 'UNDER REPAIR')], max_length=20),
        ),
    ]
