# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0014_auto_20180217_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='email_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='no_of_adults',
            field=models.IntegerField(blank=True, default=1, verbose_name='No of Adults'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='no_of_children',
            field=models.IntegerField(default=0, verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='no_of_adults',
            field=models.IntegerField(default=1, verbose_name='No of Adults'),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='no_of_children',
            field=models.IntegerField(default=0, verbose_name='Children'),
        ),
    ]
