# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0016_auto_20180222_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedrooms',
            name='resource_qty',
            field=models.IntegerField(default=1, verbose_name='Room No.'),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='service_qty',
            field=models.IntegerField(default=1, verbose_name='Room No.'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='paid',
            field=models.CharField(choices=[('YES', 'YES'), ('No', 'NO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='advance_receipt_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Advance Reciept'),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 6, 20, 18, 680511)),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='relationship',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
