# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0027_auto_20180226_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedrooms',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 15, 22, 15, 984177)),
        ),
    ]
