# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0028_auto_20180226_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedrooms',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 15, 26, 20, 146108)),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='resource_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Resources', verbose_name='Extra Resource Required'),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='resource_qty',
            field=models.IntegerField(default=0, verbose_name='Resource Quantity'),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='service_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Servicedetails', verbose_name='Service Required'),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='service_qty',
            field=models.IntegerField(default=0, verbose_name='Service Quantity'),
        ),
    ]
