# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0034_auto_20180309_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedrooms',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 2, 37, 8, 949043)),
        ),
    ]
