# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0035_auto_20180309_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='esalary_details',
            name='salary',
            field=models.IntegerField(blank=True, default=0, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='esalary_details',
            name='salary_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='esalary_details',
            name='attendance_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Eattendance_details'),
        ),
        migrations.AlterField(
            model_name='esalary_details',
            name='emp_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontdeskapp.Employee_details'),
        ),
    ]
