# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0036_auto_20180312_0231'),
    ]
