# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdeskapp', '0037_auto_20180312_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='phone_no',
            field=models.BigIntegerField(max_length=10, verbose_name='Phone'),
        ),
    ]
